# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47c8282180bbd2ec267ed06b11cf8d6a959915172dbad365ad201143b294a86ce47aadafed9641f4b655b68ed46323829e3b9ae33cf182420efad25887848e39

test:
  secret_key_base: 683cdbc7f5458a2182a9711d187da91bb518164de26c8d4181ba0a5e72692bcd05645d0c377e387567dc5c411bbc4affe3be821a27ad6d090f54d8af626918b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
